# Generated by Django 6.0.4 on 2026-04-15 17:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_borrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='borrow_date',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='borrower_name',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='return_date',
        ),
        migrations.AddField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='borrowed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrow',
            name='user',
            field=models.CharField(default='anonymous', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='myapp.book'),
        ),
    ]
